### PR TITLE
Only create wrap function when it is needed.

### PR DESCRIPTION
**Pull request by Wojbie**

### CODE REVIEW

**Review by Lemmmy — APPROVED** [review]

**Comment by SquidDev** [comment]
Would it not be possible to hoist the entire metatable out of that call? `_` will only ever take one value after all...

**Comment by Wojbie** [comment]
it's defined as `function _mt.__call(_, x)` so unless it's error `_` inside that function is the called table not luadash.

**Comment by SquidDev** [comment]
@Wojbie Yes, though it looks like the metatable is only used in one place - on the `_` table. I may be misreading the code though.

**Comment by plt-amy** [comment]
You're both right, but like, the performance cost of this is negligible.. If you wanted to save anything, hoist wrap outside of the function.

**Comment by Wojbie** [comment]
Hmm.. that means the `__index` would need to pass current local `_` to the outside warp. Not sure if that is worth it.

**Comment by plt-amy** [comment]
Local `_` is the same as the other `_`.

**Comment by Wojbie** [comment]
Unless user set "_mt" metatable on his own table. Are we not supporting that use case?

**Comment by SquidDev** [comment]
I don't see a reason to support it - I can't really see a situation where you'd want to "borrow" this lib's implementation rather than just writing your own.

**Comment by plt-amy** [comment]
No, the metatable is local to the file and not exported.

**Comment by plt-amy** [comment]
Also, are we not going to mention the fact that the function is called `wrap`...?

**Pull request closed without merging**
